### ISSUE TITLE
I don't Received my sats on my waller nor on my profile!

### ISSUE THREAD

**Issue by mtsteo** [RoboSats/robosats#1046]
Sorry i'm newbie and dont speak english very well but in a nutshell i did a trade and don'd received my sats, it disappeared! I'm sorry if i'm in wrong place to relate this!

**Comment by pcwd** [comment]
You can get support via Telegram.  Look at the bottom of the Robosats page and click on the Telegram link at the bottom of the page.

**Comment by Reckless-Satoshi** [comment]
> Sorry i'm newbie and dont speak english very well but in a nutshell i did a trade and don'd received my sats, it disappeared! I'm sorry if i'm in wrong place to relate this!

It seems this is an issue you have to raise to your coordinator or in the public support groups.

There is no known bugs of faulty payouts that are confirmed by error. In fact, everytime an order flow is finished, the buyer can downdload a summary `.json` file that contains the `preimage` (confirmation of payment). You can that one and the `payment_hash` to get in touch to your LN wallet provider for support.

Closing the issue as there is no basis to think it is related to a bug in the code base.
