### ISSUE TITLE
Cannot collaborative cancel before buyer posts invoice

### ISSUE THREAD

**Issue by Illidanek** [RoboSats/robosats#1098]
**Describe the bug**
If a buyer requests collaborative cancel after the seller locks the trade collateral, the seller cannot accept or reject the cancel.

**To Reproduce**
1. Buyer locks trade amount 
2. Seller does not post lightning invoice, but instead requests a collaborative cancel
3. Buyer is informed that the counterparty is requesting a collaborative cancel, but cannot do anything.
4. Buyer has no way of reacting to the collaborative cancel

**Expected behavior**
Buyer should have an option to request or accept the collaborative cancel.

**Comment by Reckless-Satoshi** [comment]
Hey @Illidanek . Thanks for reporting. I assume this is an issue only on the new multi-coordinator app (v0.6.0) ?

**Comment by Reckless-Satoshi** [comment]
Hey @Illidanek I just ran some tests and it works as expected.

The collaborative cancel button is only available before the "Confirm FIAT sent" button is clicked. Once that button is clicked, it is not possible to propose or accept a collaborative cancellation. This must necessarily mean your peer clicked the "Collab cancel" button and then clicked "Confirm fiat sent". The only way to be able to do a collaborative cancellation after "Fiat sent" is clicked, is by clicking "Payment failed?" and reverting the fiat sent confirmation.

That said, I just submitted a small fix so the alert "Your peer is asking for a collaborative cancel" goes away if "Confirm fiat sent" was clicked.

**Comment by Illidanek** [comment]
Hey there,

That does not address the issue I described.

I had the issue when using the new multi-coordinator app, yes. And I was the buyer (taker) and the seller wanted to collaborative cancel before we even got to the chat stage. They hadn't posted their receive invoice yet, and clicked Collaborative Cancel, while I had already locked my sell amount.

I was unable to accept the cancel until they eventually proceeded with submitting their receive invoice.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
