### ISSUE TITLE
Server not available? pending contract

### ISSUE THREAD

**Issue by nixonrichard1971** [RoboSats/robosats#1101]
I would like to settle a contract that I had open in one robot and I was waiting to get some lightning liquidity.

Since 2 days ago I can't connect to Robots using a Tor browser. I have Robosats embedded in my Tor bitcoin node and can't connect either, keeps saying "building robot" when I enter my recovery token.

Any help?
Thank you

**Comment by noeljbass** [comment]
Same issue

**Comment by Reckless-Satoshi** [comment]
Hey @nixonrichard1971 @noeljbass . The RoboSats experimental coordinator announced a maintenance stop of one week through all the communication channels starting on Feb 29th. It went into a stop only when there was no active contracts anymore, that probably means your order entered a dispute before the stop.

Your Umbrel app  (v0.5.4 or earlier) is hard-wired to the experimental coordinator. However, v0.6.0 and newer introduce multi-coordinator (decentralization). We are hosting a v0.6.0 client that can already be used at dex.robosats.com (open in Tor Browser). Soon the full release and Umbrel release will take place.

In any case, in the new client, you will also see that the Experimental coordinator is "down". So you have to wait until next week to fill in your dispute statement.

Closing this issue as it does not relate to the codebase, but to operation (and robosats coordinators have their own communication channels for that).
