### ISSUE TITLE
Telegram notifications

### ISSUE THREAD

**Issue by gabbygator184** [RoboSats/robosats#1136]
**Describe the bug**
When an order is taken and the maker robot enabled telegram notifications, the maker will receive a link via telegram to open the order in the browser and proceed. If a new Tor Browser is opened, this link will guide the user to the order screen, but without the robot token loaded.

The user might think the page is loading because he is waiting the blue spinner to disappear, but in fact an error is occurring in the backend. If the robot token is not informed, the order will be closed and the user will lose the bond.

**To Reproduce**
1. Create an order and enable telegram notifications
2. Close Tor Browser
3. Take the order with a new robot and close Tor Browser
4. Open the link received via telegram in Tor Browser
5. The order won't open (as expected) and the screen shows the blue spinner.

**Expected behavior**
An error message should be shown if someone try to open an order address without robot token or ask for the robot token.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Tor Browser
 - Front End Version: v0.6.0-alpha
 - Coordinator Version: v0.5.4 (ROBOSATS_TAG=80b97f3)

**Comment by Reckless-Satoshi** [comment]
We should display the "You need to generate an avatar" Dialog anytime someone lands on `/order/...` without a robot.

**Comment by nikkuAg** [comment]
Hey, is this issue still open? I would like to work on this

**Comment by KoalaSat** [comment]
Workflow fixed here https://github.com/RoboSats/robosats/pull/1563/files
