### ISSUE TITLE
Coordinator is not being notified for new disputes in Telegram

### ISSUE THREAD

**Issue by KoalaSat** [RoboSats/robosats#1231]
**Describe the bug**
We recently implemented a "New dispute" notification for Coordinator in Tg. It looks like it's not working

**To Reproduce**
1. Create an order with robot1
2. take it with robot2
3. Open a dispute

**Expected behavior**
The coordinator should be notified in telegram, but it looks like it's not working

**Additional context**
The ENV variable is not correctly named https://github.com/RoboSats/robosats/commit/22a93d630ddab3118493c375591327e637d43908#diff-2958cfb55111c6b7031d31ec64e90eaabcd90fab4d2ff4cbca85966f6acbab7cR142

**Comment by aaravm** [comment]
Can I be assigned the issue?
