### ISSUE TITLE
Not possible to create a second order with the same robot

### ISSUE THREAD

**Issue by KoalaSat** [RoboSats/robosats#1235]
**Describe the bug**
Reusing a robot and creating a second order after success freeze the process.

**To Reproduce**
1. Create a robot.
2. Sell something.
3. Wait until success.
4. Change agent.
5. Create another sell.
6. Bug happens.

Both orders should be created in the same coordinator.

(reported in Telegram: April 19 10:59 GMT)

**Expected behavior**
The user should be able to move forward.

**Additional context**
Truth is we are planning to not allow users to reuse robots, but this might lead to a source causing other bugs, so better to identify it and fix it.

**Comment by Reckless-Satoshi** [comment]
Thank you @KoalaSat for posting the steps to reproduce this issue. I think it also happens even if you add a new robot to the garage.

**Comment by KoalaSat** [comment]
https://github.com/RoboSats/robosats/pull/1407 fixed this issue
