### ISSUE TITLE
Api and website URL issues

### ISSUE THREAD

**Issue by Nisaba** [RoboSats/robosats#1236]
Hi,

What is the url of the API described here ?
https://learn.robosats.com/docs/api

The url used in examples (https://learn.robosats.com/api) doesn't work.

Also, I noticed a https issue on https://dex.robosats.com/ and https://unsafe.robosats.com/

Thank you

**Comment by Reckless-Satoshi** [comment]
RoboSats is a decentralized P2P exchange, therefore there is no single API endpoint. You would need to make calls to the API of each coordinator. You can find each coordinator's onion endpoints in `/frontend/static/federation.json`

For example, for Satstralia, the API URL is
```
http://satstraoq35jffvkgpfoqld32nzw2siuvowanruindbfojowpwsjdgad.onion/api
```

https://github.com/RoboSats/robosats/blob/9ae50948dd9466da697bd5e60bf0df76cd02655c/frontend/static/federation.json#L122-L131

> Also, I noticed a https issue on https://dex.robosats.com/ and https://unsafe.robosats.com/

These are Tor to Web bridges. HTTPS is not supported. These clearnet frontends do not really have any meaningful functionality. No Robosats coordinator offers Clearnet API at the moment.

**Comment by Nisaba** [comment]
Thank you !
