### ISSUE TITLE
Ring sound in the order view when the browser window changes size

### ISSUE THREAD

**Issue by rkfg** [RoboSats/robosats#125]
**Describe the bug**
Probably an effect being triggered on some re-renders. It also happens once after the order is created.

**To Reproduce**
1. Create an order
2. Change the browser window size
3. Ding-dong

**Expected behavior**
No audio signals unless the order is taken.

**Desktop (please complete the following information):**
 - OS: Debian Testing
 - Tor Browser
 - 11.0.11 (based on Mozilla Firefox 91.9.0esr) (64-bit)

**Comment by Reckless-Satoshi** [comment]
Indeed, this is a minor, yet annoying bug.

The audio is played on component refresh, most often caused when the Desktop UI switches to Mobile or vice-versa.  The variable that stores whether the sound has already been played is lost. 

A possible solution is to store that variable somewhere else more persistent. Needs research.

Thanks for opening the issue @rkfg !

**Comment by Reckless-Satoshi** [comment]
Seems to be solved by the full re-write of the TradeBox at the end of last year. Thank you @shyfire131 for cathing with this one!
