### ISSUE TITLE
android app nostr link not using njump

### ISSUE THREAD

**Issue by umk0m1qk** [RoboSats/robosats#1288]
Your in-app nostr link should direct to njump rather than Snort so that users can find & follow your npub in their default nostr client. This is the proper share link:

https://njump.me/npub1p2psats79rypr8lpnl9t5qdekfp700x660qsgw284xvq4s09lqrqqk3m82

**Comment by Reckless-Satoshi** [comment]
Good one! Thank you @umk0m1qk

**Comment by KoalaSat** [comment]
I think additionally would be great to use the nostr: protocol if we are in mobile:

```
const nostrClick = (): void => {
    if (isMobile) {
      window.location.href = `nostr:${nostrPubKey}`
    } else {
      window.open(`https://njump.me/${nostrPubKey}`, '_blank', 'noopener,noreferrer')
    }
  }
```
