### ISSUE TITLE
Android-17a077b version crashes when creating an order.

### ISSUE THREAD

**Issue by pcwd** [RoboSats/robosats#1357]
**Describe the bug**
Crashes when creating an order.

**To Reproduce**
Click Create button to create an order.

**Screenshots**
![Screenshot_20240630-103624](https://github.com/RoboSats/robosats/assets/41215821/faaff8a9-863a-4ee6-99f0-324bc7ba5085)

**Desktop (please complete the following information):**
Android-17a077b

**Smartphone (please complete the following information):**
Pixel 5

**Comment by KoalaSat** [comment]
Hi, Thanks for reporting! 

We identified the issue and it should be resolved with https://github.com/RoboSats/robosats/pull/1356/files#diff-e02f6ebe26d7454959840bd63827c5da1ffb1ff75b7e6e2fc27aecde31ebea88L3

**Comment by KoalaSat** [comment]
This issue should be solved with https://github.com/RoboSats/robosats/releases/tag/v0.6.3-alpha

**Comment by KoalaSat** [comment]
@pcwd closing this one, please don't hesitate on report again if you still find problems 🙂
