### ISSUE TITLE
Add Algerian Dinar (DZD)

### ISSUE THREAD

**Issue by abned08** [RoboSats/robosats#1406]
Hi Robosats Team,

I love the work you’re doing with Robosats! I’d like to request adding the Algerian Dinar (DZD) as a supported currency. This would help the growing number of Bitcoin traders in Algeria use your platform more easily.

Thanks for considering this addition.

**Comment by KoalaSat** [comment]
Thanks for the requests, I created the PR ready to be merged :) https://github.com/RoboSats/robosats/pull/1408/files

**Comment by KoalaSat** [comment]
> Thank you @KoalaSat, to be precise, it's DZD, not DZA.

Yeah sorru I had a fat finger there 😅
