### ISSUE TITLE
Successful spelt incorrectly in a few places

### ISSUE THREAD

**Issue by tmwclaxton** [RoboSats/robosats#1420]
super tiny nit, successful is spelt with 1 's' in a few places i.e. [here](https://github.com/RoboSats/robosats/blob/1bd38a9029fdda7a6e8a56c4e8872fc66f45f227/api/models/order.py#L49)

**Comment by KoalaSat** [comment]
Thanks for reporting! I created a PR for it https://github.com/RoboSats/robosats/pull/1421/files
