### ISSUE TITLE
Invoices from Brezz are no longer accepted

### ISSUE THREAD

**Issue by soulbless** [RoboSats/robosats#1436]
**Describe the bug**
Hello, invoices from Brezz are no longer accepted. I get the follwing error when submitting the payout invoice: "The invoice hinted private routes are not payable within the submitted routing budget".

Is this related to the [fee siphoning](https://learn.robosats.com/docs/wallets/#muun-mobile) described in your docs?

**To Reproduce**
1. As a buyer, get to step 3/5 of an order "Submit payout info"
2. Paste in a payout invoice from Breez
3. This error message is displayed: "The invoice hinted private routes are not payable within the submitted routing budget"

**Expected behavior**
Invoices from Breez used to be accepted until a few weeks ago.

**Screenshots**
![copy](https://github.com/user-attachments/assets/dc493bd9-a1de-491f-989c-f066a885b7b7)

**Desktop (please complete the following information):**
 - OS: Windows 11 and Umbrel
 - Browser: Firefox
 - Version: Umbrel-v0.6.0-alpha and mainWebsite-v0.6.3-alpha

**Comment by KoalaSat** [comment]
Hi, the payment can't be done because the fees budget is to low. Click on "Advanced Option" and there you can increase fees to try again. I would say to try first with 2k and, if not, 3k

**Comment by soulbless** [comment]
Thank you that was it! 

I opened a small PR to make it clear for a user that adjusting the budget is possible under advanced options.

**Comment by KoalaSat** [comment]
That's great thanks for contributing!
