### ISSUE TITLE
Robosats on Umbrel app store still v0.6.0-alpha

### ISSUE THREAD

**Issue by tmwclaxton** [RoboSats/robosats#1456]
**Describe the bug**
Hey, small wee issue, Robosats is still on the v0.6.0-alpha version on the Umbrel App Store.  Not sure if it takes a while for the change to propagate or if you're still working on the wee release.

https://apps.umbrel.com/app/robosats

**Comment by soulbless** [comment]
This is now showing a warning on Umbrel that the version mismatch between the coordinator and the client `might lead to a bad user experience`.

I followed this [umbrel guide](https://github.com/getumbrel/umbrel-apps?tab=readme-ov-file#32-testing-on-a-raspberry-pi-or-umbrel-home) to test [docker image v0.7.0-alpha](https://hub.docker.com/layers/recksato/robosats-client/v0.7.0-alpha/images/sha256-681d4010d62d16b788bf9b979d593a19a0ee52dad80656884e6d3deae947edda?context=explore), but that image still pulls v0.6.0-alpha for some reason.

**Comment by KoalaSat** [comment]
Answered here https://github.com/RoboSats/robosats/issues/1457

**Comment by KoalaSat** [comment]
Moving the thing :) https://github.com/getumbrel/umbrel-apps/pull/1462

**Comment by KoalaSat** [comment]
Umbrel merged it :tada:  should be available soon

**Comment by soulbless** [comment]
@KoalaSat Thanks for updating Umbrel's version! 

Though similar to what I have seen in my tests (described above), the docker image it still pulls in client version v0.6.0-alpha.

**Comment by KoalaSat** [comment]
on this case the reason is different, it's cache, you can try out by cleaning your browser cache, with a different browser or just waiting until the cache gets outdated

**Comment by soulbless** [comment]
> on this case the reason is different, it's cache, you can try out by cleaning your browser cache, with a different browser or just waiting until the cache gets outdated

Yes! `Ctrl+F5` loaded the correct version v0.7.0-alpha thank you!
