### ISSUE TITLE
Warning message not displaying actual version numbers

### ISSUE THREAD

**Issue by soulbless** [RoboSats/robosats#1457]
**Describe the bug**
When the coordinator and the client run different versions, a warning message is displayed. The message however does not show the actual version number.

**To Reproduce**
1. Run different versions between the coordinator and the client, in this example v0.6.0-alpha client on Umbrel, while to coordinator is on v0.7.0-alpha.
2. Start Robosats
3. The warning message will be displayed.

**Expected behavior**
The warning message should show the actual version numbers.

**Screenshots**
![Screenshot 2024-09-11 095240](https://github.com/user-attachments/assets/3f2d7ff9-33c4-4c1b-a6b3-9c1ed3aeef5c)

**Desktop (please complete the following information):**
 - OS: Umbrel
 - Browser Firefox
 - Version: v0.6.0-alpha

**Comment by KoalaSat** [comment]
Hi, thanks for reporting, Umbrel's requires a separate process we need to do with them to upgrade versions. I'll be moving this this week to have ASAP. In the mid-time, there is no problem with using v6 clients with v7 coordinators 👍

**Comment by KoalaSat** [comment]
Moving the thing :) https://github.com/getumbrel/umbrel-apps/pull/1462

**Comment by KoalaSat** [comment]
Umbrel merged it :tada:  should be available soon

**Comment by soulbless** [comment]
@KoalaSat Thanks for for updating Umbrel's version! Though it does not resolve this issue, this issue is about the UI not displaying the version numbers, please see the attached screenshot.
