### ISSUE TITLE
cant write a message in the chatbox while in the chatroom 

### ISSUE THREAD

**Issue by khansher296** [RoboSats/robosats#1465]
Error: Error encrypting message: Could not find valid self-signature in key c266ae7486daa7ed: Signature creation time is in the future
this is the message i am getting after typing in the chat box

**Comment by KoalaSat** [comment]
This situation appears when the other part has their machine's clock wrongly set up. 

The solution is to change to `Turtle mode` and type a `#` at the beginning of your messages
