### ISSUE TITLE
Incorrect satoshi amount listed for seller in order modal

### ISSUE THREAD

**Issue by tmwclaxton** [RoboSats/robosats#1479]
**Describe the bug**
Incorrect satoshi send amount showing up.  In this trade the seller should be sending about 97 EUR of BTC and receiving 100 EUR; however it states the seller is only sending about 18 EUR.  This is more than the bond but less than the escrow so I'm not sure where this number comes from.

![Screenshot 2024-09-16 201718](https://github.com/user-attachments/assets/8704c57a-bcf4-4831-9c62-1f8d125006aa)
(ignore the dispute resolution - instant sepa just taking a while)

Here is GET request for order if useful
`{"id":13373,"status":16,"created_at":"2024-09-15T09:21:06.607503Z","expires_at":"2024-12-25T18:22:48.263492Z","type":1,"currency":2,"amount":"100.00000000","has_range":true,"min_amount":"100.00000000","max_amount":"500.00000000","payment_method":"Instant SEPA Revolut Wise Strike","is_explicit":false,"premium":"3.49","satoshis":null,"maker":109013,"taker":109022,"escrow_duration":28800,"bond_size":"4.00","latitude":null,"longitude":null,"total_secs_exp":8640000,"is_maker":true,"is_taker":false,"is_participant":true,"maker_nick":"*REDACT*","maker_hash_id":"*REDACT*","maker_status":"Active","taker_status":"Inactive","is_buyer":false,"is_seller":true,"taker_nick":"*REDACT*","taker_hash_id":"*REDACT*","status_message":"Wait for dispute resolution","is_fiat_sent":true,"is_disputed":true,"ur_nick":"*REDACT*","satoshis_now":178229,"maker_locked":false,"taker_locked":false,"escrow_locked":false}`

**To Reproduce**
This may be occurring on all orders or only ones in dispute.

**Comment by tmwclaxton** [comment]
It appears to be related to the robosats update, when viewing the offer on v0.6 the sat amount is correct.  It also appears to soley be a front-end issue as when viewing the invoice on RTL the escrow amount is correct.

![WhatsApp Image 2024-09-16 at 21 04 28_40d67001](https://github.com/user-attachments/assets/e73eb58d-40bb-43f5-aa1a-1b82f30e4789)

**Comment by KoalaSat** [comment]
Thanks for reporting! As you described the bug is merely visual and has been already fixed in the main branch https://github.com/RoboSats/robosats/pull/1477 it will be included in the next release

**Comment by KoalaSat** [comment]
Fixed with https://github.com/RoboSats/robosats/releases
