### ISSUE TITLE
Tor error in API

### ISSUE THREAD

**Issue by Nisaba** [RoboSats/robosats#1520]
Hi,

I use RoboSats API to get offers since a couple of months and it worked well.
But since a few days, I get this error:
"An error occurred while establishing a connection to the proxy tunnel"

The TOR connection can't be established anymore...

Is there a breaking change from your side ?

Thank you for your help !

**Comment by KoalaSat** [comment]
Hi! what's the onion address you are using?

**Comment by Nisaba** [comment]
these ones :
https://raw.githubusercontent.com/RoboSats/robosats/9ae50948dd9466da697bd5e60bf0df76cd02655c/frontend/static/federation.json

**Comment by KoalaSat** [comment]
Experimental and Satstralia are permanently off. I would recommend to always use the most recent version of that JSON file https://github.com/RoboSats/robosats/blob/main/frontend/static/federation.json

**Comment by Purchase73** [comment]
Is it not okay to just go to dex.robosats.com? I can't remember where I found that, but I believe it was supposed to be the way to access robosats.

**Comment by Nisaba** [comment]
> Experimental and Satstralia are permanently off. I would recommend to always use the most recent version of that JSON file https://github.com/RoboSats/robosats/blob/main/frontend/static/federation.json

Yes, it works now; Thanks

**Comment by KoalaSat** [comment]
> Is it not okay to just go to dex.robosats.com? I can't remember where I found that, but I believe it was supposed to be the way to access robosats.

Yes, with a Web browser this is right. But this issue qas about acceaing coordinator's api. Every coordinator is an independent server. So far you need to access to all to them to get the idea of the global book.

That was until we started posting all orders to nostr 🙂, following releases will take advantage of this to improve user experience.
