### ISSUE TITLE
Extra spaces not handled properly in input field of recovery token

### ISSUE THREAD

**Issue by HamzaIbrahimi** [RoboSats/robosats#1532]
**Describe the bug**
When trying to recover an existing robot with a saved token, the input field does not handle trailing spaces properly and fails to find your robot. I almost had a heart attack thinking I had saved the wrong key, luckily it was just an extra space at the end of the input field. 

**To Reproduce**
1. Go to the robosats page and generate a token. Save it and exit tor.
2. Open robosats and click recovery.
3. Add your saved key and add a space at the end or beginning of key.
4. Result: Fails to find your robot.

**Expected behavior**
Copy and paste the key and generate my robot with my saved key.

**Desktop (please complete the following information):**
 - Mac OS: 
 - Chrome
 - Version 130.0.6723.58

**Additional context**
Please add trim() to the input field

**Comment by KoalaSat** [comment]
I was indeed refactoring this view, so I just add it https://github.com/RoboSats/robosats/pull/1526/commits/a79d3c2330c58e383718588ea12f5cd34debe814

Closing this issue. Will be included in v0.7.2

**Comment by HamzaIbrahimi** [comment]
Awesome! Thank you guys for this amazing service!
