### ISSUE TITLE
[MacOS] Stuck at loading screen

### ISSUE THREAD

**Issue by dani69654** [RoboSats/robosats#1585]
**Describe the bug**
Cannot access [robosats onion](robodexarjwtfryec556cjdz3dfa7u47saek6lkftnkgshvgg2kcumqd) using Tor browser. 
The page is stuck at the initial loading screen.

**_It works when trying to access the website via Brave browser (under tor)_**

**Desktop (please complete the following information):**
 - OS: MacOs 14.5 (23F79)
 - Browser: Tor
 - Version: 14.0

**Comment by KoalaSat** [comment]
Hi! Can you check if you have your browser security settings set to Standard?

**Comment by dani69654** [comment]
I had it set to `safer`, works with `standard` indeed. Thanks!
