### ISSUE TITLE
Add core-lightning as LN node provider.

### ISSUE THREAD

**Issue by Reckless-Satoshi** [RoboSats/robosats#196]
**Is your feature request related to a problem? Please describe.**
We are currently relying on [LND](https://github.com/lightningnetwork/lnd) for RoboSats backend node. It does work pretty well. There is only a few things that might be critical: channel.db is hard to manage and performance/reliability could still be better (I guess?). 

It would be great to implement [core-lightning](https://github.com/ElementsProject/lightning) as backend, not as a replacement, but for exploration and extra redundancy. The higher performance and use of Postgres as database would be much appreciated. While it is not clear yet whether there will be some shenanigan or unexpected issue, the redundancy of having two node providers will always be of great value.

If core-lightning is available as node provider, future effort to improve RoboSats availability could be put into creating a "LN load balancer" that will smartly direct invoice creation / payments to a pool of nodes of different providers.

**Describe the solution you'd like**

We need a new [`api/lightning/node.py`](https://github.com/Reckless-Satoshi/robosats/blob/main/api/lightning/node.py) (LNnode provider) that can perform all of the same functions using core-lightning as backend instead of LND. 

- [ ] **Prerequisites not met** By @louneskmt we need a hodl invoice plugin in Core-Lightning. Out of scope for RoboSats.
- [ ] The first step would be to add a [core-lightning container](https://hub.docker.com/r/elementsproject/lightningd/tags) running testnet3 to our dev [docker-compose](https://github.com/Reckless-Satoshi/robosats/blob/main/docker-compose.yml) orchestration. 
- [ ] It might be useful to implement unit tests `test.node.py` to learn about the current set up. The unit tests will be very helpful in the future, as they should receive exactly the same behavior regardless of whether the call was attended by LND or core-lightning  in any future release of these.
- [ ] The bigger chunk of the work: write all core-lightning calls for every function.

I am unsure how big this task really is. But it certainly requires some very specific knowledge on interacting with Lightning node APIs.

**Additional context**
This task is ⚡**rewarded with 2M Sats**⚡ . Drop a comment if you want to be assigned.

**Comment by louneskmt** [comment]
Hey! I can try to take care of this task.

**Comment by Reckless-Satoshi** [comment]
> Hey! I can try to take care of this task.

Assigned! Good luck, this is a challenging task :) Reach us via @robosats in Telegram if you need help setting up the dev stack.

**Comment by louneskmt** [comment]
Would it be okay to use the Unix Domain Socket + the official Core Lightning python client to communicate with the node? I initially planned to use their new gRPC plugin to avoid the use of a new library, but it is still missing useful methods (like for decoding pay requests). The main python service would need access to the file socket (path).

**Comment by Reckless-Satoshi** [comment]
Sounds good to me. Have no experience with it, but I guess we can mount a file socket into several containers (c-lightning and robosats services) using a volume mount.

**Comment by louneskmt** [comment]
We can definitely do that with Docker, however it won't work on macOS (only on Linux). It is a known "won't solve" Docker issue. I learnt it the hard way a couple of months ago, after several hours of debugging lol

https://github.com/docker/for-mac/issues/483

**Comment by Reckless-Satoshi** [comment]
> however it won't work on macOS (only on Linux)

Sad, it means a chunk of the stack won't work on the machines of many potential robo-developers 🤔 Are you in macOS? Not an issue for RoboSats operation as it mostly relies on ubuntu server.

**Comment by louneskmt** [comment]
Yeah... Alternatively, I can look for all the missing gRPC methods and implement them on the plugin on Core Lightning. Maybe there are not that much (I gotta admit I've just checked if `decodepay` was there). They are missing anyway. We would then need waiting for a new Core Lightning release in order to use my changes with Robosats.

**Comment by Reckless-Satoshi** [comment]
> Yeah... Alternatively, I can look for all the missing gRPC methods and implement them on the plugin on Core Lightning.

Maybe this missing gRPC method (decodepay) can be sustituted by the json-RPC one? In any case, all the creative freedom to you :) If you think the plugin is a better solution, let's do it. 

How hard would it be for us to build our own temporary Core Lightning image? There is no rush for this robosats feature, it will certainly take a lot of testing until we are comfortable to use it in the wild with real users.

**Comment by leshik** [comment]
You might want to use `socat` as a workaround to [expose the UNIX domain socket over TCP](https://serverfault.com/questions/517906/how-to-expose-a-unix-domain-socket-directly-over-tcp).

**Comment by louneskmt** [comment]
AFAIU Core Lightning doesn't natively support hold invoices creation. However, it does provide a plugin hook `invoice_payment` that notify when a payment is coming in before actually settling the HTLC. It is possible to use that to retain the HTLC settlement, and thus add support for hodl invoices. I couldn't find an existing plugin adding hodl invoices creation support using this. 

We would need to implement such plugin, but I'm not sure yet of the amount of work needed.

**Comment by Reckless-Satoshi** [comment]
Haven't played with c-lightning myself. I see the `CreateinvoiceRequest` method asks for the Preimage param, but it probably retains the preimage and uses it to autosettle invoices on arrival. Also the method to query invoice status seem to only be able to return EXPIRED, PAID, UNPAID. We need the equivalent of ACCEPTED (LOCKED). We would also benefit from having CANCELLED, but not totally needed.

No experience with Core Lightning plugin, but sounds like the challenging task keeps getting harder :sweat_smile:

**Comment by louneskmt** [comment]
Yeah, looks like a full "hodl invoice" plugin needs to be written for Core Lightning. This is gonna be a bit too complex for me, so unfortunately I'm gonna have to drop this issue. 

Happy to take care of the Robosats part if someone writes the plugin tho!

**Comment by Reckless-Satoshi** [comment]
I think that building this plugin is a bit far from the scope of RoboSats.

Not familiar with Core-Lightning development, are plugins developed in the main repository? It seems so. I have found a couple explicit mentions to "hold invoice" in the tests ([link](https://github.com/ElementsProject/lightning/blob/ade10e7fc4dacbb9d635b05152c7dc38c0896ce7/tests/plugins/hold_invoice.py)) and an old thread on the implementation of `htlc_accepted` hook(https://github.com/ElementsProject/lightning/pull/2267). Also found online explicit mentions of how Core Lightning plugins would allow new capabilities such as 'hodl invoices' back in 2019. However there does not seem to be such plugin or anyone working on it (at least I could not find). 

**Is the best way to proceed to simply open an issue and hope it eventually gets done?**


> Happy to take care of the Robosats part if someone writes the plugin tho!

I am un-assigning you and moving this task to a different category ("prerequisites not met"). Let me tip you with a bit of positive karma (40K Sats) for the valuable research you have done. Please share an invoice with long expiration time from a _non-sensitive node_id_ :)
