### ISSUE TITLE
Bugs/Issues found in Robosats v0.2.1 Alpha Android app 

### ISSUE THREAD

**Issue by OSFr0g** [RoboSats/robosats#278]
I've been testing the wrong version the previous hours. 

Edit: After some testing, I found 2 minor issues. Will continue testing tomorrow, tor is dead now. 

### **Describe the bug**
- Download robot info button does not work in the main page
![IMG_20221011_032707.jpg](https://user-images.githubusercontent.com/108383157/194977016-34c89580-9a66-4f5b-a89f-82a77f5bb035.jpg)
- When disabling stealth invoices, it sometimes auto-enables again when you go back to robot profile.

---

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi Note 10
 - OS: Android 11 / MIUI 12.5.7
 - Browser: Robosats App :metal:
 - Version: v0.2.1.alpha

**Comment by Reckless-Satoshi** [comment]
Long time fixed, this issue was not closed in time.
