### ISSUE TITLE
Android app not usable over torbox wlan or orbot VPN mode

### ISSUE THREAD

**Issue by alaznem** [RoboSats/robosats#378]
**Describe the bug**
When using a torified connection like a torbox wlan or an orbot VPN mode, establishing another tor connection over tor through the robosats app fails as expected 

**To Reproduce**
Use Orbot in VPN mode or connect to a torbox wlan or similar torified connection Proton VPN with tor server might work as well to reproduce, but this is untested.

**Expected behavior**
The app should do a ping of the robosats onion site and only spin up an orbot or whatever you're using under the hood if there is no tor connection already.

As alternative: let the user disable spinning up a tor proxy within the app.

**Comment by Reckless-Satoshi** [comment]
Hey @alaznem ,

Thanks a lot for reporting and opening this issue,this one will be a bit tough to solve as the untorified webview will not find onion sites even if Orbot is on (At least on my tests).

A tested work around solution for Orbot in VPN mode is to go to Orbot Settings and disable RoboSats from the apps listed. As for Torbox wlan I do not think there is any solution.

**Comment by alaznem** [comment]
> This one will be a bit tough to solve as the untorified webview will not open onion sites even if Orbot is on (at least on my tests).

Thank you for having a look at this and a first guess about the work needed.

> A tested work around solution for Orbot in VPN mode is to go to Orbot Settings and disable RoboSats from the apps listed. This solution is about the same amount of work as `As alternative: let the user disable spinning up a tor proxy within the app.` . However for Torbox wlan I do not think there is any work around.

:heavy_check_mark: This works if the user doesn't use Full Device VPN mode in Orbot.

:x: However, if the user uses Full Device VPN mode* in Orbot, this is not an option and I can't think of any orbot setting to workaround #378. This usage type of Orbot is probably not widely used, however it provides the best protection from IP leaking. Just as sidenote: the real IP does leak for sure in one way or another, if you don't use a dedicated tor router like torbox in front of your Android device.


*Full Device VPN mode is characterized by not selecting any app and therefore having all data routed through the Orbot VPN. See screenshot below.
![](https://nostr.build/i/nostr.build_477b77bed552575f6eec496bbad4dcad46047d0dde4132d36a8b0f6c29a20ffd.jpg)

**Comment by KoalaSat** [comment]
I have been using the new App with Orbot in VPN for a while now. You just need to disable the engine:

![Screenshot_20241125-012110](https://github.com/user-attachments/assets/d2556cae-9d67-4361-ba06-760e2c0812ec)
