### ISSUE TITLE
Streamlining Robot Recovery Process using Unique Token in URL

### ISSUE THREAD

**Issue by k0gen** [RoboSats/robosats#387]
The current process for recovering an existing robot using the token is time-consuming and requires multiple clicks. It would be great if we could streamline the process and make it more user-friendly.

One way to achieve this would be to allow users to directly enter the robot's unique token in the URL, which would take them to the "Welcome back!" page. For example, typing /robot/X1gZ9zcYu1QRBFZJpgWwXY50IJad7YDecPay in the address bar would automatically load the recovery page for the corresponding robot.

Implementing this feature would greatly improve the user experience and make it easier for users to recover their robots.

**Comment by Reckless-Satoshi** [comment]
Implemented in https://github.com/RoboSats/robosats/pull/512
