### ISSUE TITLE
Can't read qr code with dark UI

### ISSUE THREAD

**Issue by bota87** [RoboSats/robosats#426]
Black and white are inverted on dark mode and it's really hard to read the qr codes

**Comment by Reckless-Satoshi** [comment]
While inverted QR codes are not technically part of the specification, these are widely readable by most modern scanners. Inverted QR codes are friendly with the dark theme (no white flashes), so it is unlikely we go back only light QR codes. Two possible solutions for the user:

1) Use a QR that reads mirrored and inverted QR codes (Open source one: SecScanQR https://github.com/Fr4gorSoftware/SecScanQR).
2) Switch to light theme.

**Comment by bota87** [comment]
I've tried with an android 13 (POCO F3), with the system reader and with [this app](https://play.google.com/store/apps/details?id=com.google.zxing.client.android) the results are the same, the white version get easily read, the black version almost never.

I put here the screenshots that I've made to do this test if someone else would like to try

![image](https://user-images.githubusercontent.com/52842374/233437402-71b82f97-fa40-4b25-81c2-1fca5c35f8ae.png)
![image](https://user-images.githubusercontent.com/52842374/233437453-2ea94770-f9ea-4bf7-92e5-7bdc16a9db20.png)

**Comment by Reckless-Satoshi** [comment]
A possible solution is to add a new setting in the Settings tab for "Only light QR codes". This one should only be visible if the selected theme is Dark, and will allow users to keep using the Dark theme but display always QR codes.

**Comment by Reckless-Satoshi** [comment]
Implemented in https://github.com/RoboSats/robosats/commit/298ce130f715210d87629d2df6086919fa35e4e0
