### ISSUE TITLE
It's difficult to enter a discount because the field forces a zero into it

### ISSUE THREAD

**Issue by stevenroose** [RoboSats/robosats#532]
The premium field somehow forces a 0 into itself. So when you type 1, it will type 01, you can't backspace the 0. Typing a `-` will hence be ignored because `0-` doesn't make sense. So the only way to input a discount is to use the left arrow, type `-` to get `-0`, then if you want 5% discount you type `5` to get `-50` and then you remove the `0` in the end.

Pretty annoying. Can the premium field just be a regular field without the 0 being forced into it?

**Comment by Reckless-Satoshi** [comment]
> The premium field somehow forces a 0 into itself. So when you type 1, it will type 01, you can't backspace the 0. Typing a `-` will hence be ignored because `0-` doesn't make sense. So the only way to input a discount is to use the left arrow, type `-` to get `-0`, then if you want 5% discount you type `5` to get `-50` and then you remove the `0` in the end.
> 
> Pretty annoying. Can the premium field just be a regular field without the 0 being forced into it?

Hey @stevenroose , thanks for bringing this up!

In my small test it seems easy to enter a discount by first entering `-` then the number. However, it is true that if there is a value (for example, you enter a positive number and change your mind), it will always place a `0`. Then it gets annoying as you need to use the arrows. Looks easy to fix! :D

**Comment by stevenroose** [comment]
I noticed this only happens when you empty the field. On the first edit, you can enter `-10` without an issue, but when you err and want to correct, empty the field, it will force a 0 into it.

**Comment by JooVLC** [comment]
@Reckless-Satoshi, Can I try to fix this?

**Comment by Reckless-Satoshi** [comment]
> @Reckless-Satoshi, Can I try to fix this?

Assigned :D
