### ISSUE TITLE
Error reproducing the setup docs to run frontend with docker

### ISSUE THREAD

**Issue by JooVLC** [RoboSats/robosats#585]
**Describe the bug**
I cannot execute the step-by-step in the [docs](https://github.com/RoboSats/robosats/blob/main/setup.md#with-docker) to run the frontend with docker in my PC. I don't know if it's a forgot step, or error in my configuration, or because I am in a _Windows_ system.

**To Reproduce**
1. Clone the project
2. Execute the step-by-step in the [docs to run the frontend with docker](https://github.com/RoboSats/robosats/blob/main/setup.md#with-docker)

**Expected behavior**
I expected to follow the setup and run a self-hosting robosats in "http://localhost:12596", as it's in the documentation.

**Screenshots**
![image](https://github.com/RoboSats/robosats/assets/30505180/3f062e3a-52d8-43dd-9751-cc7ca71e814b)

**Desktop (please complete the following information):**
 - OS: Windows 11 (WSL 2 - Ubuntu)
 - Browser Chrome
 - Version 113.0.5672.93 (Official version) 64 bits

**Additional context**
I noticed the "static" file inside the nodeapp folder, and after changing the "static" file to a folder "static" with a .gitkeep the error stopped and I managed to run the `docker-compose up` command with sucess. Is it a possible solution (PR to do or change in docs) or is really a configuration error in my side? Following below prints of the fix in my local machine to run:

- **Before the fix**:
  - ![image](https://github.com/RoboSats/robosats/assets/30505180/9f1cc618-4b60-4d5a-ae40-8092c891f147)
- **After fix**:
  - ![image](https://github.com/RoboSats/robosats/assets/30505180/9d335b44-6cd6-4f62-90c4-464026f44fc1)
  - ![image](https://github.com/RoboSats/robosats/assets/30505180/5707aefa-de54-44ce-a7e6-22885a68955c)
  - ![image](https://github.com/RoboSats/robosats/assets/30505180/6842f300-5256-43b6-ada4-0f33b33af57e)

**Comment by Reckless-Satoshi** [comment]
This is a Windows issue. The "file" `/nodeapp/static` is a symbolic link to `/frontend/static` . For windows, symbolic links do not exist: it's interpreted as a blank file.

If I understand well what happened, your fix works (well, you could have just deleted `/nodeapp/static` and it would have worked too). However, it breaks the nodeapp Dockerfile and the `docker-compose-example.yml` as these rely on the symlink (yet, only works on Linux / Max).

Let me push a fix with a solution where it works both linux/windows, so you can give another try

**Comment by Reckless-Satoshi** [comment]
Actually this should probably be enough https://github.com/RoboSats/robosats/commit/fd8f64e93ae174ee1a275fb9704256d3cad96723 . Let me know if this works.

The nodeapp now cannot be built without first copying or symlinking `/frontend/static` . But the GH workflow does the copying and leaving a comment on the Dockerfile seems enough as of now :D

**Comment by JooVLC** [comment]
> This is a Windows issue. The "file" `/nodeapp/static` is a symbolic link to `/frontend/static` . For windows, symbolic links do not exist: it's interpreted as a blank or text file.
> 
> If I understand well what happened, your fix works (well, you could have just deleted `/nodeapp/static` and it would have worked too). However, it breaks the nodeapp Dockerfile and the `docker-compose-example.yml` as these rely on the symlink (yet, only works on Linux / Max).
> 
> Let me push a fix with a solution where it works both linux/windows, so you can give another try

I tested just delete the `/nodeapp/static`, the `docker-compose up` worked, but the local run of robosats not worked with the follow error:

![image](https://github.com/RoboSats/robosats/assets/30505180/3e9685aa-19a1-41b1-bc5b-a9ba84a4dbc0)

**Comment by JooVLC** [comment]
> Actually this should probably be enough [fd8f64e](https://github.com/RoboSats/robosats/commit/fd8f64e93ae174ee1a275fb9704256d3cad96723) . Let me know if this works.
> 
> The nodeapp now cannot be built without first copying or symlinking `/frontend/static` . But the GH workflow does the copying and leaving a comment on the Dockerfile seems enough as of now :D

I will try now, ty. I'll reply if it worked or not as soon as I can.

**Comment by JooVLC** [comment]
> > Actually this should probably be enough [fd8f64e](https://github.com/RoboSats/robosats/commit/fd8f64e93ae174ee1a275fb9704256d3cad96723) . Let me know if this works.
> > The nodeapp now cannot be built without first copying or symlinking `/frontend/static` . But the GH workflow does the copying and leaving a comment on the Dockerfile seems enough as of now :D
> 
> I will try now, ty. I'll reply if it worked or not as soon as I can.

It works, ty.

![image](https://github.com/RoboSats/robosats/assets/30505180/885e49ca-e126-4c9e-9ca5-441d8668956b)
![image](https://github.com/RoboSats/robosats/assets/30505180/7c60fbfc-df99-465b-8c03-ab4897c05190)
