### ISSUE TITLE
Command "python collect_phrases.py" doesn't work as intended in windows OS.

### ISSUE THREAD

**Issue by JooVLC** [RoboSats/robosats#590]
**Describe the bug**
When executing the command `cd frontend/static/locales; python collect_phrases.py`, needed to complete any PR with new phrases to the user interface, the order of the phrases inside the json is not the same in Windows and Linux.

**To Reproduce**
1. Use Windows OS
2. Clone the project
3. Run the command `cd frontend/static/locales; python collect_phrases.py`

**Expected behavior**
The order of the phrases generated by the command `cd frontend/static/locales; python collect_phrases.py` be the same in all OS.

**Screenshots**
N/A - The error is well documentaded in the **Additional context** area.

**Desktop (please complete the following information):**
 - OS: Windows 11 (WSL 2 - Ubuntu)
 - Browser N/A
 - Version  N/A

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS:  N/A
 - Browser N/A
 - Version  N/A

**Additional context**
The script `collect_phrases.py` uses the function `os.walk` to get all the phrases in the frontend, and the order of the dirs and files returned by the function is not guaranteed as the [oficial documentations](https://docs.python.org/3/library/os.html#os.walk) states.

The problem was found in https://github.com/RoboSats/robosats/pull/577#pullrequestreview-1426253266, and discussed in https://github.com/RoboSats/robosats/pull/577#issuecomment-1548350871 and https://github.com/RoboSats/robosats/pull/577#issuecomment-1548671905

**Comment by JooVLC** [comment]
I will take care of the bug myself, like said in https://github.com/RoboSats/robosats/pull/577#issuecomment-1548350871.

**Comment by Reckless-Satoshi** [comment]
Thank you @JooVLC for finding out this platform dependent issue and the will to solve it :rocket:
