### ISSUE TITLE
Remove linting errors on frontend

### ISSUE THREAD

**Issue by cdmoss** [RoboSats/robosats#591]
**Describe the bug**
There are a great number of linting errors in the frontend code

I would be willing to clean these up using sane adjustments to the eslint config and any other necessary refactors.

**Comment by Reckless-Satoshi** [comment]
Hey @cdmoss indeed, this is a needed task. 

A large part of the client app is a bit type-unsafe. Most of the lint issues are however straight-forward to fix, just time consuming. So unless eslint is relaxed to stupidly useless level, the amount of work of this task can be pretty large. It's hard to evaluate beforehand. Let's make this a rewarded task for **400.000K Sats**

**Comment by Reckless-Satoshi** [comment]
Hey @cdmoss any update on the state of this task. 

Is it correct that you were adding some fixes to this branch https://github.com/cdmoss/robosats/tree/the-federation-layer-v0.5.0 ?

Cheers!
