### ISSUE TITLE
Adds sounds to Android App

### ISSUE THREAD

**Issue by Reckless-Satoshi** [RoboSats/robosats#618]
**Is your feature request related to a problem? Please describe.**
Sounds do not work on the Android webview app. The web app makes sounds work when the order is taken, etc. 

**Describe the solution you'd like**
We could make the sounds work by sending a message up to the react-native wrapper and playing sounds using react-native libraries.

In a similar fashion to our already implemented methods in `systemClient` to handle clipboard and cookies, we could add methods to handle sounds.

This task is rewarded with :zap: 400K Sats :zap:

**Comment by tarunsamanta2k20** [comment]
I'm interested to work on it. But I wanna know more about the issue.

**Comment by Reckless-Satoshi** [comment]
Hey @tarunsamanta2k20 ,

Our mobile app (in `/mobile`) is a simple Webview wrapper of our web app. The `index.html`, `main.js` and static files (including the sounds) are bundled within our Android APK (in `/mobile/html/Web.bundle`). On our webapp, on the browser, sounds like this:

https://github.com/RoboSats/robosats/blob/5d5435e7a100af85eb4d928919c35ea675c1df86/frontend/src/components/Notifications/index.tsx#L213C8-L215

https://github.com/RoboSats/robosats/blob/5d5435e7a100af85eb4d928919c35ea675c1df86/frontend/src/components/Notifications/index.tsx#L34-L39

It would be great to find a solution so the Audio works in both: web browser, and Webview (loading the local file). It is likely that sounds do not play in Webview simply because the path to the files is different when they have to be read locally from `/mobile/html/Web.bundle` (they would likely be `file:///`), we usually just use the condition `window.NativeRobosats != undefined ? ... ` to have a different behavior when the webapp is running within the webview. This might be a straight forward 1 line fix. However, playing sounds and notifications from `outside the webview`  (e.g., passing a message to the react-native wrapper by building new `frontend/src/services/systemClient` method) might be a more elegant solution that can be expanded into a join solution for this task and https://github.com/RoboSats/robosats/issues/619

Let me know if you want to give it a try :D

**Comment by tarunsamanta2k20** [comment]
@Reckless-Satoshi   I want to give it a try, but wanna know in which interface sound is not working, a web browser or Android app?

**Comment by Reckless-Satoshi** [comment]
> which interface sound is not working, a web browser or Android app?

Android App. I kept digging into it to be more clear and ended up fixing it the sounds (commit https://github.com/RoboSats/robosats/commit/f6601922b80ab339484b ). Given that the sound does now work on the Android app, I think it is better to focus on the notifications task https://github.com/RoboSats/robosats/issues/619 and close this issue. Would you like to take a look at that task? We do definitely need a hand with it! :D

**Comment by Reckless-Satoshi** [comment]
Closing as sounds do now work (only if the app is open or recently open).
