### ISSUE TITLE
Add Currency: Bangladeshi Taka (BDT) Missing on RoboSats

### ISSUE THREAD

**Issue by valhalla1913** [RoboSats/robosats#648]
**Is your feature request related to a problem? Please describe.**
Bangladeshi Taka (BDT), the currency of Bangladesh is missing in RoboSats

**Describe the solution you'd like**
Add BDT in the list of currencies.

**Describe alternatives you've considered**
No other alternative. 
**Additional context**
Bangladesh is a major growth market for Bitcoin users. It has one of the largest population on Earth. I have friends in Bangladesh who are using CEX P2P exchanges with KYC and looking for alternatives. Some of them complained about the missign currency in RoboSats.

**Comment by Reckless-Satoshi** [comment]
Hey @valhalla1913 

The only constrain to add new currencies is to have reliable public pricing. The two integrated APIs are https://api.yadio.io/exrates/BTC and https://blockchain.info/ticker . It seems BDT is in yadio.io , so if you want to go head you can open a PR to add it into RoboSats, it is pretty simple, here an example of @HT696 adding IRT: https://github.com/RoboSats/robosats/pull/412

**Comment by dapsavoie** [comment]
Hi @Reckless-Satoshi ,

I made a pr for these changes 
https://github.com/RoboSats/robosats/pull/659

Please let me know if this is sufficient. I did read the guidelines but its my first contribution so if feedback is appreciated.

thanks
