### ISSUE TITLE
Market debth chart is wrong

### ISSUE THREAD

**Issue by Impa10r** [RoboSats/robosats#674]
I go to see market, choose a specific currency (say RUB), the list of offers is displayed (very few if any). I click on chart, it shows many different levels. Same chart if I go to see swaps. Is it always showing BTC/USD?

**Comment by Reckless-Satoshi** [comment]
> Is it always showing BTC/USD?

The depth chart shows all offers, always. If you select RUB, it prices the X axis in RUB.

**Comment by Impa10r** [comment]
Then it serves no practical purpose, except to show that there are some offers in some currencies somewhere. That said, why does the chart show that I can buy from 0% premium, but the list is only from 1%?

I there a statistics of volume traded somewhere?

-------- Original Message --------

**Comment by Reckless-Satoshi** [comment]
> I there a statistics of volume traded somewhere?
> I there a statistics of volume traded somewhere?

There are curated plots in [learn.robosats.com/stats](https://learn.robosats.com/stats) You could also fetch the raw data yourself using the API [unsafe.robosats.com/api](https://unsafe.robosats.com/api)


I get, you prefer to see a chart only with the orders available for a currency, makes sense. Let's explore subsetting the data of the Depth Chart according to the currency selected!
There are curated plots in [learn.robosats.com/stats](https://learn.robosats.com/stats) You could also fetch the raw data yourself using the API [unsafe.robosats.com/api](https://unsafe.robosats.com/api)

I get, you prefer to see a chart only with the orders available for a currency, makes sense. Let's explore subsetting the data of the Depth Chart according to the currency selected!

**Comment by Impa10r** [comment]
Thanks a lot, glad to see the usecase growing! Any chance I could filter out liquidity swaps?

**Comment by Impa10r** [comment]
Hello again, would you be interested in a dual-funded channel?

https://LightningNetwork.Plus/swaps/17016

-------- Original Message --------
