### ISSUE TITLE
Add WASM module to build robot identities on the client 

### ISSUE THREAD

**Issue by Reckless-Satoshi** [RoboSats/robosats#713]
**Is your feature request related to a problem? Please describe.**
The RoboSats client generates a token and uses its hash as robot identity. The second hash of the token is used to generate a robot Nickname and a Robohash avatar, however, this work is done by the remote API (coordinator). Given that we are transitioning to a multi-coordinator setup, ideally, the client should be able to generate the fancy robot avatar and nickname by itself, without needing to request this work to any coordinator. 

By enabling the clients to create both the avatar and the nicknames locally, the full abstraction of a "Robot identity" will live only on the clients: the coordinators only know the hash string (i.e., their IDs). For example, coordinators will only have to stream the hash string to clients for every maker when they send the order book, instead of sending every `avatar.webp`, then the clients can create all avatars locally. This will allow coordinators to be lighter (computing the avatar is probably one of the heaviest tasks the coordinator does) and save on bandwidth which in turns might make operating a robosats coordinator very cheap and accessible even in low end hardware and poorly connected regions. It will in addition, remove the last centralization point: the creation of robot avatars.

**Describe the solution you'd like**
1. Build a Rust workspace project that uses [RoboHash-rust ](https://github.com/kyco/robohash)crate (or better, make RoboSats fork with [our own art](https://github.com/RoboSats/Robohash)). Re-write also the module [NicknameGenerator](https://github.com/RoboSats/robosats/tree/main/api/nick_generator) in Rust.

2. The new crates ( two modules , e.g. `Robohash` generator and `Robonames`) will compute the hash and return a Base64 image and a String nickname.

3. Write tests for known hashes in python and known nicknames and profile images and confirm they do work and behavior is identical!

4. Build a WASM (maybe use `wasm-pack`?) module and use in frontend as a mean to generate the robot images purely on the frontend. 

Now the frontend holds the full abstraction of robots. There is no need for a designated "central" coordinator to do the task of generating avatars. Load times and bandwidth should also be greatly reduced!

To be researched: can we compress all the needed robot component `.png` pars into WEBP base64 strings and embed them into the WASM ?? Otherwise, can the robot parts be turned into vector graphics? Or at least, can we decimate the number of images to only need one `.png` per part (currently there is one image for every color)? The full set of robot parts in `.png` and at high resolution are about 6.5 MB, I am sure we can make the whole space of robot avatars fit under 1MB!

**Additional context**
This task is the start of the "Oxidation" (use of Rust) of RoboSats! :crab: 

We are not adding a Sats reward to this task as I am looking forward to learn some Rust and work on it myself :smile: but I would rather pair-code or share the task with some experienced rustacean!

**Comment by Reckless-Satoshi** [comment]
There is some progress:
Here the `robo-identities` cargo workspace https://github.com/reckless-satoshi/robo-identities
The `robo-identities-wasm` is 760KB (Robohash avatar generator only) or 1.1MB robohash and nickname generator.
The robohash generator embeds all of the robot parts, so having the `.wasm` is the only asset needed for the client to generator robots. It can generate up to 1,293,692,400 different robots, which is quite a lot more than the original RoboHash. This is due to the fact that the color is programmatically computed via hue rotation, instead of sticking to the same 8 colors of the `.png` files (was also needed to save of size).

Here the WIP PR to integrate it into RoboSats app https://github.com/RoboSats/robosats/pull/735 . Given that computing an avatar takes ~200ms, computing all avatars in the book is blocking rendering. Therefore, the avatar generation is moved to webworkers. It works like a charm, and avatars can be generated and cached even before the book is opened. 

Unfortunately, it does not work on the Android Webview app, I am looking for fixes, but possibly is an issue with the relative paths in Android... might be solved by inlining the webworker and wasm.

**Comment by secondl1ght** [comment]
Great progress, looking forward to trying it out!

**Comment by Reckless-Satoshi** [comment]
Hey @secondl1ght this module is now in production in RoboSats v0.6.0 and it seems to work alright! The initial release is in NPM https://www.npmjs.com/package/robo-identities-wasm
