### ISSUE TITLE
How to run a RoboSats Coordinator need better guidance

### ISSUE THREAD

**Issue by cadayton** [RoboSats/robosats#820]
Need better guidance on how to become a RoboSats Coordinator.

Currently, running my own lightning node (SANJOSE_UBETCHA) which is implemented using BTCPayServer docker images and running LND lightning node.  This is being host off a linux VM running in Oracle Cloud.

**Comment by Reckless-Satoshi** [comment]
At the moment the only guide available is to take a look at the development `robosats/docker-compose.yml` and figure out how to adapt to your specific setup.

I suggest, for this very initial time, coordinators first learn to run the development `docker-compose.yml`. That will give you quite some confidence and knowledge of how things run. Then adapt to your node.

In the near future we will release production ready `docker-compose.yml` and StartOS app. Guides for custom builds or specific setups like `BTCPayServer` will probably never exist. But if you want to dig into it yourself, we can offer help in the GitHub issues everytime you encounter a roadblock or errors.

**Comment by Reckless-Satoshi** [comment]
Hey @cadayton, we now have `robosats-deploy` repository that contains an example docker-compose orchestration to run a production ready coordinator https://github.com/RoboSats/robosats-deploy/tree/main/compose
The readme has step by step instructions on how to install and run everything on a new machine from scratch. This should serve as base to adapt for your custom setup.

You can open new issues in that repository if you have doubts or find things worth improving. Closing this issue.
