### ISSUE TITLE
Deposit Invoive still blocked after calcel the order 

### ISSUE THREAD

**Issue by jedimosca1** [RoboSats/robosats#904]
* I canceled an order which I made on robosats without receiving any interested parties, but the return of the locked invoice of xxxxx sats were not made.

* Basically the deposit was not returned after cancellation BEFORE any party accepts my order, as it has always been returned if the cancellation is made without interested parties or automatically when the advertisement deadline expires. However, unfortunately this did not happen this time, hence my contact.

**Expected behavior**
Please unblock my deposit.

**Desktop (please complete the following information):**
 - OS: iOS 
 - Browser: Tor Browser
 - Version 13.0

**Comment by Reckless-Satoshi** [comment]
Hey @jedimosca1

I edited your message for your privacy. GitHub Issues is the place for reporting bugs or proposing new features. If you have issues with the operation of an specific RoboSats coordinator, please use the suitable channel to communicate with the coordinator support.

In any case, the RoboSats backend will always cancel the invoices as soon as you click "Cancel" on orders that have not been taken. Therefore, it is most likely that either 1) this `in_flight` payment is in hold by some routing node or 2) your LN wallet did not realize yet that this payment has failed. Running your own LN node would rule out 2) as you will be always able to tell instantly if a payment failed. Note that even if the RoboSats coordinator "forgets to cancel" the invoice, it would anyway cancel automatically in ~48h maximum.

Closing this issue as it does not relate to improvements to the codebase.
