### ISSUE TITLE
[federation]: coordinator 'Satstralia'

### ISSUE THREAD

**Issue by KoalaSat** [RoboSats/robosats#924]
### Coordinator Alias

Satstralia

### Avatar

![](https://satstralia.com/logo192.png)

### Description

I'm happy to be part of Robosats in so many ways! 

### Motto

btc = ɔʇq

### Color

#329239

### DevFund Donations

33%

### PGP Public Key and Fingerprint

https://keys.openpgp.org/vks/v1/by-fingerprint/D1894C9862A9D02D47D96C84AE30B6904210DA14

### Privacy Policy

- Evidence in Disputes: In the event of a dispute, users will be asked to provide transaction-related evidence. This could include transaction IDs, screenshots of payment confirmations, or other pertinent transaction records. Personal information or unrelated transaction details should be redacted to maintain privacy.

- Short-term Storage: Sensitive information related to disputes will be stored only for the duration necessary to resolve the issue. Once resolved, the data will be permanently deleted.
    For ease of use e-mail communications are permitted, but E2EE and decentralized platforms such as NOSTR, SIMPLEX and MATRIX are advised.

### Data Policy

- No Third-Party Sharing: Under no circumstances will user information be shared with third parties

- Short-term Storage: Any log needed to operate the coordinator will be cleared after 7 days, unless strictly needed to process disputes. To ensure utmost privacy, the coordinator will be accessible only through TOR.

### Other Policies

- Do not share personal information through the chat, unless strictly needed for completing the trade.
- Any dispute can be fist address through our public chats in the different social networks but never will be started using private chats.

### Onion Mainnet Coordinator Service Address

http://satstraoq35jffvkgpfoqld32nzw2siuvowanruindbfojowpwsjdgad.onion

### Onion Testnet Coordinator Service Address

https://qu6xztmzhlve6nxbb77jldek53pvhkaltz6seni7wq6g6yyj233qp4yd.onion

### Clearnet Mainnet Coordinator Service Address

https://unsafe.satstralia.com

### Clearnet Testnet Coordinator Service Address

https://test.unsafe.satstralia.com

### Mainnet Pubkey(s)

029c5b14214ca7c1f5334db539dbab266088ba43a40563551efb9458756a94cd94

### Testnet Pubkey(s)

03607900c00c5fcc3f9d32da4ad687c73d95df4faa065e5320e77b41c5d76ef381

### 1. email

info@satstralia.com

### 2. SimpleX

https://simplex.chat/contact/#/?v=1-4&smp=smp%3A%2F%2FZKe4uxF4Z_aLJJOEsC-Y6hSkXgQS5-oc442JQGkyP8M%3D%40smp17.simplex.im%2Fq0pIyShcBl0EP8le0D0xy2OfSrP1mQWg%23%2F%3Fv%3D1-2%26dh%3DMCowBQYDK2VuAyEAcwmsC9GQwQEt40UNpYp4vKPhU_UnWXsXcVl-OJ57lC4%253D%26srv%3Dogtwfxyi3h2h5weftjjpjmxclhb5ugufa5rcyrmg7j4xlch7qsr5nuqd.onion&data=%7B%22type%22%3A%22group%22%2C%22groupLinkId%22%3A%22vNcyZH9C3eE6MHzRNpR3xA%3D%3D%22%7D

### 3. Matrix

#satstralia:matrix.org

### 4. Nostr

npub1z94lxjf7m5snda0qc6s3kmpy6r4nfw74h78da9j6j4y8ym08zrrs459wpr

### 5. Website

https://satstralia.com

### 6. Telegram

@satstralia

### RoboSats Federation Basis

- [X] I accept the basis of the RoboSats Federation

**Comment by KoalaSat** [comment]
- Testnet: Working ✅ 
- Mainnet: Downloading blockchain ⌛

**Comment by Reckless-Satoshi** [comment]
Welcome to the federation **Satstralia** ! :rocket:
> ### Motto
> 
> btc = ɔʇq
10/10 :rofl: 



> ### PGP Public Key and Fingerprint
> 
> https://keys.openpgp.org/verify/1JF6Dur8nJjxyayJgYOg7ORhdydYGlotZG9gAvPxACU

There seems to be an issue with this link.

Coordinator added to `federation.json` here https://github.com/RoboSats/robosats/pull/922/commits/47731b6ee863604b66ef8c1f7919bb2ec493ea47

**Comment by KoalaSat** [comment]
> There seems to be an issue with this link.

 https://keys.openpgp.org/vks/v1/by-fingerprint/D1894C9862A9D02D47D96C84AE30B6904210DA14

**Comment by KoalaSat** [comment]
@Reckless-Satoshi I'll probably change the onion address at least for testnet next week

**Comment by KoalaSat** [comment]
Testnet onion updated to https://testraliar7xkhos2gipv2k65obykofb4jqzl5l4danfryacifi4t7qd.onion
