### ISSUE TITLE
Api link is broken

### ISSUE THREAD

**Issue by douglaz** [RoboSats/robosats#942]
It points to https://learn.robosats.com/docs/api-v0.1/ and there is no https://learn.robosats.com/docs/api-v0.5.3/

**Comment by Reckless-Satoshi** [comment]
Good catch, the right location is https://learn.robosats.com/docs/api/

Commit https://github.com/RoboSats/robosats/commit/09215be8a9e6a0879e3fba3a28d172bbf52cefc7 fixes the navigation link in the docs to point to the right location.
