### ISSUE TITLE
Add Albanian LEK currency

### ISSUE THREAD

**Issue by HostFat** [RoboSats/robosats#974]
Can you add the support for listing LEK (Albania currency) offers?

https://en.wikipedia.org/wiki/Albanian_lek

There is also a payment system for Albania citizens: https://easypay.al/

**Comment by Reckless-Satoshi** [comment]
Hey @HostFat we can only add currencies for which there are prices in the public APIs used by the coordinators. It seems LEK is not there in https://blockchain.info/ticker, https://api.yadio.io/exrates/BTC . Maybe you could reach the folks at Yadio and ask if they can add LEK?

**Comment by HostFat** [comment]
Yep, I'll try this :)

**Comment by Reckless-Satoshi** [comment]
Hey @HostFat that's great. I added ALL to the project as well https://github.com/RoboSats/robosats/commit/07830fd2fd8fb9e60a6ae6bd060fbb7230c3d98c, it should be available after the next release.

**Comment by Reckless-Satoshi** [comment]
Hey @HostFat that's great. I added ALL to the project as well https://github.com/RoboSats/robosats/commit/07830fd2fd8fb9e60a6ae6bd060fbb7230c3d98c, it should be available after the next release.
